# Generated by Django 5.1 on 2025-01-06 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeedeatail_empcode_employeeeducation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='comapny1duration',
            new_name='coursegra',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='comapny2duration',
            new_name='coursehsc',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='comapny3duration',
            new_name='coursepg',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company1name',
            new_name='coursessc',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='comapny1desig',
            new_name='schoolclggra',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='comapny2desig',
            new_name='schoolclghsc',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='comapny3desig',
            new_name='schoolclgpg',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company1salary',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company2name',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company2salary',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company3name',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company3salary',
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagehsc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagepg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagera',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagessc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='schoolclgssc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='yearofpassinghsc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='yearofpassingra',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1name', models.CharField(max_length=100, null=True)),
                ('comapny1desig', models.CharField(max_length=200, null=True)),
                ('company1salary', models.CharField(max_length=100, null=True)),
                ('comapny1duration', models.CharField(max_length=100, null=True)),
                ('company2name', models.CharField(max_length=100, null=True)),
                ('comapny2desig', models.CharField(max_length=200, null=True)),
                ('company2salary', models.CharField(max_length=100, null=True)),
                ('comapny2duration', models.CharField(max_length=100, null=True)),
                ('company3name', models.CharField(max_length=100, null=True)),
                ('comapny3desig', models.CharField(max_length=200, null=True)),
                ('company3salary', models.CharField(max_length=100, null=True)),
                ('comapny3duration', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
