# Generated by Django 5.1 on 2025-01-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_comapny1duration_employeeeducation_coursegra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='yearofpassingssc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
